### ISSUE TITLE
ValueSet edqm-darreichungsform hat keine deutschen display values

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/medikationsplanplusplus#11]
Wie kommt man da vom UKF-Code zu einer menschenlesbaren Darstellung??

**Comment by simoneOnFhir** [comment]
Aus der Kommunikation mit Kai:

Ich sehe die Nutzung der FHIR-Profile überwiegend auf der _konsumierenden_ Seite des UKF für Applikationen, die sich primär an den _Patienten_ wenden.

Also muss man ja von dem, was im UKF enthalten ist, irgendwie zu einer patientenfreundlichen Darstellung gelangen.
Folglich muss es irgendwo einen Terminolgieserver geben, der 
a) das ValueSet kennt und
b) die $lookup-Operation beherrscht http://build.fhir.org/codesystem-operations.html#lookup
mir eine Antwort auf die Frage GET [base]/CodeSystem/$lookup?system=urn:oid:0.4.0.127.0.16.1.1.2.1&code=12200 geben kann.

Für Prototyp-Implementierungen könnte das aber auch tx.fhir.org übernehmen. Wir müssten dazu nur die CodeSystem-Resourcen (mit geeigneten Display-Values) dort hochladen.

Das nächste Problem ist, dass ja auch der Name des Medikamentes (_und_ ggf. die Darreichungsform) aus der PZN ermittelt werden muss um aus dem UKF etwas konsumierbares zu machen. Das wiederum wäre von einem Terminologie-Server zuviel verlangt.
Da bräuchten wir einen Server, der alle Positionen aus dem PZN-Katalog als Medication-Resourcen hostet und den man mit der Frage GET [base]/Medication?code=http://fhir.de/CodeSystem/ifa/pzn&code=02078897 belästigen kann und der eine komplett ausgefüllte Medication-Ressource incl. Darreichungsform und sämtlichen Display-Values zurückliefert.

Anders geht es ja eigentlich gar nicht...

Und wenn das ohnehin die Prämisse ist, dann sollten wir darüber nachdenken, in den Profilen zuzulassen, dass ein Medikament nur durch seinen Identifier referenziert wird,
also statt in der MedicationList zu schreiben
    <entry>
        <item>
            <reference value="Medicationstatement/medicationstatement-1"/>
        </item>
    </entry>
und eine Medication-Resource zu bundeln, die eigentlich außer der PZN nichts verwertbares enthält,
wäre für "Fertig-"Medikament sinnvoller:
     <entry>
        <item>
            <identifier>
                <system value ="http://fhir.de/CodeSystem/ifa/pzn"/>
                <value value ="12200"/>
            </identifier>
        </item>
    </entry>

Denn wenn man es eh' nachschlagen muss, dann reicht auch das eindeutige Kriterium für den Lookup.
Außerdem müssten die Inhalte der Ressource ja über alle Medikationspläne hinweg statisch sein.

...was mich gerade zu der Erkenntnis bringt, dass offensichtlich bei der Medication-Resource der identifier schlicht vergessen wurde!?
Ich werde das mal klären...

Eine Medication-Resource explizit zu übermitteln wäre ja nur dann erforderlich, wenn es sich um eine Rezeptur handelt.

Wie ist das denn aktuell im Projekt geplant? Wie komme ich von einer PZN zum Namen des Medikamentes bzw. zur Darreichungsform?

**Comment by simoneOnFhir** [comment]
Diskussion um logical reference und Medication.identifier ist hinfällig, da die Medication im MedicationStatement alternativ auch als CodableConcept referenziert werden kann.

**Comment by simoneOnFhir** [comment]
Laut https://standardterms.edqm.eu/ gibt es Deutsche Display Values, diese müssen also noch in das ArtDecor-ValueSet eingepflegt werden.

**Comment by kheitmann** [comment]
Postponed: diese sollen in SPOR (EMA) aus deren offiziellen Zusammenstellungen herausgeholt werden. Bis auf Weiteres werden die deutschen Übersetzungen daher nicht gehandhabt.

IFA Codes müssen aber zu de EDQM gemapt werden. Ursula Tschorn (DIN) fragen, da sie die IDMP Sachen für Deutschland macht.

Die deutschen Übersetzungen liegen (vom DIMDI erzeugt) vor, im Rahmen des eHDSI Projekts erstellt. Frage ist, ob wir die nicht haben können.

**Comment by simoneOnFhir** [comment]
ValueSet mit deutschen Display values aus ArtDecor exportiert. Allerdings sind die deutschen Bezichner nur als Designations, nicht as Display enthalten, daher nach wie vor Validierungsfehler.
ValueSet in CodeSystem konvertiert in der absicht, eine Deutsche expansion zu erzeugen, language-parameter für expansion wird jedoch von HAPI nicht unterstützt.

**Comment by simoneOnFhir** [comment]
Erledigt: Expansion von test.fhir.org erhalten.
