### ISSUE TITLE
Composition:  Sections sollten grundsätzlich englische Bezeichner haben

### ISSUE THREAD

**Issue by psosm** [hl7germany/medikationsplanplusplus#12]
betroffen:

 Composition.section:medikationsplanSection
 Composition.section:allergienSection
 Composition.section:gesundheitsBelange
 Composition.section:klinischeParameter
 Composition.section:einverstaendnisSection
 Composition.section:hinweiseSection

**Comment by pscholz-dedalus-labor** [comment]
wäre ein negativ minor Comment im Ballot

**Comment by kheitmann** [comment]
Das ist nur der Name vom Slice und entspricht den Vorgaben des Datensatzes.

**Comment by pscholz-dedalus-labor** [comment]
Interessante Art von ballot resolution

**Comment by kheitmann** [comment]
?
Das wäre dann ein nicht-konstruktiver Kommentar.

Diese Namen sind nirgendwo sichtbar außer im Slice. Was soll der Grund sein, dort nicht synchron mit den Bezeichnen des Datensatzes zu gehen?

**Comment by pscholz-dedalus-labor** [comment]
Zu 1) eine Person entscheidet das ihn ein Kommentar nicht überzeugt und schliesst das issue. 
Das deckt sich nicht mit meiner Vorstellung von Consensus-Standard

Zu 2) Der Grund ist der Sprachbruch innerhalb eines Wortes, das geht nun einmal überhaupt nicht

**Comment by kheitmann** [comment]
Naja.
zu 1) Das ist der Ergebnis der Ballot-Reconciliaton von heute mit 7 Teilnehmern, die sich auf dem Interoperabilitätsforum dazu gemeldet haben. Dass dies nicht daraus hervorgeht, dass nur einer (ich in diesem Falle) den Kommentar schreibt, obwohl es die Meinung der Gruppe war kann ich nur bitten zu entschuldigen. Aber offensichtlich haben wir hier noch keine "Standard" das deutlich zu machen.
zu 2) ...sagt eine Person. Die anderen waren eben nicht der Meinung. Das ist glaube ich Konsensus, aber wie gesagt fehlt es noch an Vorschlägen, wie man das in den Kommentierungen deutlich machen kann...

**Comment by lhitc** [comment]
zu 1): Ich schlage vor, dass wir den Zeitraum der Reconsiliation-Kommentare bis auf Weiteres im README dieses GitHub-Repositories vermerken, evtl. mit Namen der Teilnehmer

**Comment by lhitc** [comment]
Ich war so frei, das README entsprechend zu erweitern.
