### ISSUE TITLE
MedicationStatement.taken (1..1) hat keinen korrespondierende Definition im Leitfaden

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/medikationsplanplusplus#13]
Wie ist damit umzugehen? Weg-Constrainen geht nicht. Fixieren auf "na"? Oder auf "y", weil es eine ungeschriebene Prämisse des Medikationsplans ist, dass nur Medikamente aufgeführt werden, die der Patient auch tatsächlich einnimmt? Auf jeden Fall müsste "n" untersagt werden, da dies ein unzulässiger Modifier wäre.

**Comment by kheitmann** [comment]
In R3 wird dieses auf MedicationStatement.taken = na

Hinweis: In R4 kommt das Element nicht mehr vor, sondern wird über den MedicationStatement.status abgehandelt

**Comment by simoneOnFhir** [comment]
Erledigt
