### ISSUE TITLE
MedicationStatement.dosage.dose[x] lässt keinen Freitext zu 

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/medikationsplanplusplus#14]
In FHIR ist mit MedicationStatement.dosage.dose[x] keine Freitextbeschreibung der Einzeldosis (doseQuantity) möglich, wie im IG gefordert:
http://wiki.hl7.de/index.php?title=IG:Patientenbezogener_Medikationsplan_Plus#Einzeldosierungen.
Extension?

**Comment by simoneOnFhir** [comment]
Lösung vorgeschlagen: https://chat.fhir.org/#narrow/stream/german.20(d-a-ch)/topic/.5Bmpp.5D.20Issue.20.2314.3A.20Freitext.20f.C3.BCr.20dose.5Bx.5D

**Comment by kheitmann** [comment]
Im Profil nur noch anzupassen (Slice... Freitext)

**Comment by simoneOnFhir** [comment]
Definition von dosage.doseQuantity.unit = "Menschenlesbare repräsentation der Dosierungseinheit oder Freitext für die Dosierung" bei den morgens/mittags/abends/nachts-Slices hinzugefügt

**Comment by simoneOnFhir** [comment]
done
