### ISSUE TITLE
Practitioner.organisazion fehlt

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/medikationsplanplusplus#15]
Im Leitfaden sind drei verschiedene Identifier für author.representedOrganization definiert:
http://wiki.hl7.de/index.php?title=IG:Patientenbezogener_Medikationsplan_Plus#CDA_author_.28pmp.29
Diese sind in der Pactitioner-Ressource noch nicht abgebildet. Allerdings lässt [Practitioner](http://hl7.org/implement/standards/fhir/practitioner.html) auch keine direkte Referenz auf Organisation zu. Die Zuordnung Practitioner<-->Organisation geht über [PractitionerRole](http://hl7.org/implement/standards/fhir/practitionerrole.html).

**Comment by patrick-werner** [comment]
Es wurde ein ChangeRequest in HL7Gforge Tracker erstellt:
https://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=13745

**Comment by simoneOnFhir** [comment]
Zusammengeführt mit Issue #22
