### ISSUE TITLE
NamingSystem für Apotheken ID (IDF) ist nicht spezifiziert

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/medikationsplanplusplus#16]
siehe CDA: author.representedOrganization:

Beispiel für Apotheke mit IDF Nummer:
```.xml
<representedOrganization classCode="ORG" determinerCode="INSTANCE">  
  <id root="1.2.276.0.76.4.197" extension="3379589"/>  
  <name>Sonnen-Apotheke</name>
</representedOrganization>
```

Sollte das als Organization.identifier in die DE Basis-Profile übernommen werden?

**Comment by simoneOnFhir** [comment]
https://chat.fhir.org/#narrow/stream/german.20(d-a-ch)/topic/.5Bmpp.5D.20Issue.20.2316.3A.20NamingSystem.20f.C3.BCr.20Apotheken.20ID.20(IDF).20fehlt

**Comment by simoneOnFhir** [comment]
Lösungsvorschlag wie hier diskutiert: https://chat.fhir.org/#narrow/stream/german.20(d-a-ch)/topic/.5Bmpp.5D.20Issue.20.2316.3A.20NamingSystem.20f.C3.BCr.20Apotheken.20ID.20(IDF).20fehlt
erstellt und NamingSystem in Basisprofil aufgenommen.

**Comment by kheitmann** [comment]
Identifier des Erstellers ist ein Organisations-Identifier
Namiung System muss noch angepasst werden.
