### ISSUE TITLE
In den FHIR-Profilen die Item-Nummern referenzieren

### ISSUE THREAD

**Issue by lhitc** [hl7germany/medikationsplanplusplus#18]
In den FHIR-Profilen sollten in der Beschreibung die Item-Nummern (Abschnitt 4.2) benannt werden.

**Comment by kheitmann** [comment]
Nein, die Mappings finden als Verbindung statt zwischen Datensatzkonzepten und den CDA Templates bzw FHIR Elementen bzw UKF Elementen und wird in der Datenelement-Übersicht (4.2) dann auch mit sichtbar gemacht.

**Comment by kheitmann** [comment]
Siehe #25
