### ISSUE TITLE
Mapping zwischen FHIR, CDA und UKF

### ISSUE THREAD

**Issue by lhitc** [hl7germany/medikationsplanplusplus#19]
Das Mapping von FHIR nach UKF und vice versa sowie idealerweise auch bidirektional FHIR/CDA sollte als mapping in den FHIR-Profilen enthalten sein (XPath bzw. Konstanten).

**Comment by kheitmann** [comment]
Das Mapping zwischen den drei Formaten geschieht in ART-DECOR außerhalb der jeweiligen Artefakte.

**Comment by kheitmann** [comment]
Siehe #25
