### ISSUE TITLE
X_PMP Ersatz

### ISSUE THREAD

**Issue by kheitmann** [hl7germany/medikationsplanplusplus#29]
Der Code der Composition war vorher im X_PMP aus LOINC angegeben, das wird nun angepasst an den echten LOINC Code wie folgt

<coding>
   <system value="http://loinc.org"/>
  <code value="77603-9"/>
  <display value="Medication treatment plan.extended Document"/>
</coding>

**Comment by simoneOnFhir** [comment]
korrigiert auf 77603-9
