### ISSUE TITLE
Patient Instructions

### ISSUE THREAD

**Issue by kheitmann** [hl7germany/medikationsplanplusplus#30]
in Medication Statement muss Dosage . patientInstruction möglich sein (zurzeit 0..0), es ist die an den Patienten gerichtete Instruktion.
Die steht nun in dosage 1..5 morgensmittagsabendzurnacht, ist aber per Medication Statement anzugeben.
Vielleicht muss man hier auch erstmal Medication Statement . note nehmen

**Comment by lhitc** [comment]
note ist jetzt hierfür gedacht.
dosage.patientInstruction überall auf 0..0 gesetzt.
