### ISSUE TITLE
List validation error (HAPI): http://fhir.hl7.de:8080/baseDstu3/List/78/$validate

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/medikationsplanplusplus#36]
"issue": [
    {
      "severity": "error",
      "code": "processing",
      "diagnostics": "Failed to call access method"
    }
  ]

Beispiele:
http://fhir.hl7.de:8080/baseDstu3/List/78/$validate
http://fhir.hl7.de:8080/baseDstu3/List/80/$validate

**Comment by simoneOnFhir** [comment]
List profile validiert nicht: http://fhir.hl7.de:8080/baseDstu3/StructureDefinition/List/$validate

**Comment by lhitc** [comment]
Duplikat von #48, daher hier geschlossen.
