### ISSUE TITLE
Fehler im Beispiel: humanname-own-name kommt doppelt vor

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/medikationsplanplusplus#49]
Hab's schon im Zulip geschrieben, aber hier nochmal der Nachvollziehbarkeit halber:

hier ist noch ein Fehler in den Beispielen (und damit vermutlich im Mapping):

      <family value="Graf von und zu Wernersen">
         <extension url="http://fhir.de/StructureDefinition/humanname-namenszusatz">
            <valueString value="Graf"/>
         </extension>
         <extension url="http://hl7.org/fhir/StructureDefinition/humanname-own-name">
            <valueString value="von und zu"/>
         </extension>
         <extension url="http://hl7.org/fhir/StructureDefinition/humanname-own-name">
            <valueString value="Wernersen"/>
         </extension>
      </family>
humanname-own-name darf nur einmal vorkommen,
das "von und zu" muss die url "http://hl7.org/fhir/StructureDefinition/humanname-own-prefix" haben

**Comment by kheitmann** [comment]
Ich habe die Konversionsroutine angepasst
